import type { BotConfigRow } from '../bot-config-repository';

// Demo 主 Bot 配置
export const DEMO_MAIN_BOTS: BotConfigRow[] = [
  {
    id: 'demo-bot-1',
    name: '通用客服Bot',
    description: '处理常见客服咨询，可委派子Agent处理专项问题',
    system_prompt: '你是一个专业的电商客服助手，请用礼貌、专业的语气回答客户问题。',
    tools: ['order_query', 'logistics_query', 'refund_action'],
    knowledge_ids: ['demo-ki-1'],
    skill_group_id: 'demo-sg-1',
    is_default: true,
    parent_bot_id: null,
    delegation_prompt: null,
    collaboration_config: null,
    is_sub_agent: false,
    status: 'active',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-bot-2',
    name: '售后专用Bot',
    description: '处理退换货和售后问题',
    system_prompt: '你是一个专业的售后服务助手，帮助客户处理退货、换货、维修等问题。',
    tools: ['order_query', 'refund_action'],
    knowledge_ids: ['demo-ki-2'],
    skill_group_id: 'demo-sg-2',
    is_default: false,
    parent_bot_id: null,
    delegation_prompt: null,
    collaboration_config: null,
    is_sub_agent: false,
    status: 'active',
    created_at: '2026-02-01T00:00:00Z',
  },
];

// Demo 子Agent 配置（与主Bot一起在 bot-config-repository.ts 的 list() 中使用）
export const DEMO_SUB_AGENTS: BotConfigRow[] = [
  {
    id: 'demo-sub-1',
    name: '订单处理专家',
    description: '专门处理订单查询、修改地址、取消订单等订单相关问题',
    system_prompt: '你是 SmartAssist 的订单处理专家。你专门负责处理与订单相关的问题，包括查询订单状态、修改收货地址、取消订单、查看订单详情等。请用专业、高效的语气帮助客户解决订单问题。如果遇到非订单相关的问题，请告知客户将转接给其他专家处理。',
    tools: ['order_query', 'logistics_query'],
    knowledge_ids: ['demo-ki-1'],
    skill_group_id: null,
    is_default: false,
    parent_bot_id: 'demo-bot-1',
    delegation_prompt: '当用户询问订单状态、物流信息、修改地址、取消订单等与订单直接相关的问题时，委派给此子Agent',
    collaboration_config: { can_collaborate_with: ['demo-sub-2', 'demo-sub-3'], communication_mode: 'async' },
    is_sub_agent: true,
    status: 'active',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-sub-2',
    name: '退款处理专家',
    description: '专门处理退款申请、退款进度查询、退款争议等问题',
    system_prompt: '你是 SmartAssist 的退款处理专家。你专门负责处理与退款相关的问题，包括申请退款、查询退款进度、处理退款争议、退款政策解释等。请用耐心、体贴的语气帮助客户解决退款问题。如果需要同时处理订单问题，可以与订单处理专家协作。',
    tools: ['refund_action', 'order_query'],
    knowledge_ids: ['demo-ki-2'],
    skill_group_id: null,
    is_default: false,
    parent_bot_id: 'demo-bot-1',
    delegation_prompt: '当用户申请退款、查询退款进度、退款纠纷、退款政策等与退款直接相关的问题时，委派给此子Agent',
    collaboration_config: { can_collaborate_with: ['demo-sub-1', 'demo-sub-3'], communication_mode: 'async' },
    is_sub_agent: true,
    status: 'active',
    created_at: '2026-03-02T00:00:00Z',
  },
  {
    id: 'demo-sub-3',
    name: '售后维权专家',
    description: '专门处理退换货、维权投诉、质量问题等售后问题',
    system_prompt: '你是 SmartAssist 的售后维权专家。你专门负责处理退换货、维权投诉、商品质量问题、收货纠纷等售后问题。请用耐心、公正的语气帮助客户解决售后问题，保护消费者权益的同时维护店铺利益。',
    tools: ['order_query', 'refund_action'],
    knowledge_ids: ['demo-ki-2'],
    skill_group_id: null,
    is_default: false,
    parent_bot_id: 'demo-bot-1',
    delegation_prompt: '当用户反映商品质量问题、要求换货、投诉维权、收货纠纷等售后问题时，委派给此子Agent',
    collaboration_config: { can_collaborate_with: ['demo-sub-1', 'demo-sub-2'], communication_mode: 'async' },
    is_sub_agent: true,
    status: 'active',
    created_at: '2026-03-03T00:00:00Z',
  },
];
