import type { Conversation, Message } from '@/lib/types';

// Demo 对话数据 - 买家会话
export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'demo-conv-1',
    title: '订单退款咨询',
    status: 'active',
    message_count: 8,
    source: 'web',
    priority: 'normal',
    unread_count: 2,
    rating: null,
    summary: '客户询问订单退款进度，已告知3-5个工作日到账',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'demo-conv-2',
    title: '产品质量投诉',
    status: 'handoff',
    message_count: 12,
    source: 'qianniu',
    priority: 'urgent',
    unread_count: 1,
    rating: null,
    summary: '客户反映收到的商品有质量问题，要求退货退款',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'demo-conv-3',
    title: '物流配送咨询',
    status: 'ended',
    rating: 5,
    message_count: 5,
    source: 'web',
    priority: 'normal',
    unread_count: 0,
    summary: '客户询问快递配送时间，已提供运单号和预计送达时间',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'demo-conv-4',
    title: '尺码选择帮助',
    status: 'active',
    message_count: 6,
    source: 'doudian',
    priority: 'normal',
    unread_count: 3,
    rating: null,
    summary: '客户咨询尺码选择，身高170cm体重65kg推荐M码',
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'demo-conv-5',
    title: '商品缺货咨询',
    status: 'active',
    message_count: 4,
    source: 'web',
    priority: 'normal',
    unread_count: 1,
    rating: null,
    summary: '客户询问心仪商品何时补货，已告知预计到货时间',
    created_at: new Date(Date.now() - 5400000).toISOString(),
    updated_at: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: 'demo-conv-6',
    title: '优惠券使用问题',
    status: 'ended',
    rating: 4,
    message_count: 7,
    source: 'qianniu',
    priority: 'normal',
    unread_count: 0,
    summary: '客户咨询满减优惠券使用方法，已详细说明使用规则',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-conv-7',
    title: '地址修改请求',
    status: 'handoff',
    message_count: 9,
    source: 'web',
    priority: 'urgent',
    unread_count: 0,
    rating: null,
    summary: '客户要求修改收货地址，地址已修改成功',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'demo-conv-8',
    title: '会员积分兑换',
    status: 'active',
    message_count: 3,
    source: 'doudian',
    priority: 'normal',
    unread_count: 2,
    rating: null,
    summary: '客户咨询会员积分可兑换的礼品选项',
    created_at: new Date(Date.now() - 900000).toISOString(),
    updated_at: new Date(Date.now() - 450000).toISOString(),
  },
  {
    id: 'demo-conv-9',
    title: '发票开具咨询',
    status: 'ended',
    rating: 5,
    message_count: 4,
    source: 'web',
    priority: 'normal',
    unread_count: 0,
    summary: '客户要求开具增值税专用发票，已告知开票流程',
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'demo-conv-10',
    title: '退换货流程咨询',
    status: 'active',
    message_count: 5,
    source: 'qianniu',
    priority: 'normal',
    unread_count: 1,
    rating: null,
    summary: '客户咨询7天无理由退换货的具体流程和要求',
    created_at: new Date(Date.now() - 2700000).toISOString(),
    updated_at: new Date(Date.now() - 600000).toISOString(),
  },
];

// Demo 消息数据 - 买家会话多轮对话
export const DEMO_MESSAGES: Message[] = [
  // 订单退款咨询 (demo-conv-1)
  {
    id: 'demo-msg-1-1',
    conversation_id: 'demo-conv-1',
    role: 'user',
    content: '你好，我有一笔订单想申请退款，请问多久能到账？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-msg-1-2',
    conversation_id: 'demo-conv-1',
    role: 'assistant',
    content: '您好！感谢您的咨询。退款申请审核通过后，款项会在3-5个工作日内退回到您的原支付账户。请问您的订单号是多少？我帮您查询一下具体进度。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 3500000).toISOString(),
  },
  {
    id: 'demo-msg-1-3',
    conversation_id: 'demo-conv-1',
    role: 'user',
    content: '订单号是 ORD20240615001，我已经申请退款3天了',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 3400000).toISOString(),
  },
  {
    id: 'demo-msg-1-4',
    conversation_id: 'demo-conv-1',
    role: 'assistant',
    content: '我帮您查询了一下，您的退款申请已于6月18日审核通过，预计最晚6月23日到账（以实际到账为准）。由于是周末可能会顺延，还请您耐心等待，如有其他问题随时联系我。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 3300000).toISOString(),
  },
  {
    id: 'demo-msg-1-5',
    conversation_id: 'demo-conv-1',
    role: 'user',
    content: '好的，谢谢！',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 2000000).toISOString(),
  },
  {
    id: 'demo-msg-1-6',
    conversation_id: 'demo-conv-1',
    role: 'assistant',
    content: '不客气！请问还有其他可以帮到您的吗？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 1900000).toISOString(),
  },

  // 产品质量投诉 (demo-conv-2) - 已转人工
  {
    id: 'demo-msg-2-1',
    conversation_id: 'demo-conv-2',
    role: 'user',
    content: '收到货后发现衣服有个破洞，质量太差了',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'demo-msg-2-2',
    conversation_id: 'demo-conv-2',
    role: 'assistant',
    content: '非常抱歉给您带来不好的体验！请问您方便拍张破损处的照片发给我吗？我这边帮您申请退换货处理。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 7100000).toISOString(),
  },
  {
    id: 'demo-msg-2-3',
    conversation_id: 'demo-conv-2',
    role: 'user',
    content: '【图片】你看这个破洞，就在袖口那里',
    message_type: 'image',
    image_url: 'https://picsum.photos/400/300?random=1',
    sources: null,
    created_at: new Date(Date.now() - 7000000).toISOString(),
  },
  {
    id: 'demo-msg-2-4',
    conversation_id: 'demo-conv-2',
    role: 'assistant',
    content: '感谢您发来的照片，确实可以看到袖口处有破损。这种情况我们承担全部责任。为您安排退货退款处理，请问您方便寄回吗？我们会补偿您8元运费。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 6900000).toISOString(),
  },
  {
    id: 'demo-msg-2-5',
    conversation_id: 'demo-conv-2',
    role: 'user',
    content: '我要求直接退款，不想寄回去了，太麻烦了',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 6800000).toISOString(),
  },
  {
    id: 'demo-msg-2-6',
    conversation_id: 'demo-conv-2',
    role: 'assistant',
    content: '理解您的心情。对于这种明显质量问题，我们可以为您申请极速退款，请您提供支付宝账号，我这边为您提交申请。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 6700000).toISOString(),
  },
  {
    id: 'demo-msg-2-7',
    conversation_id: 'demo-conv-2',
    role: 'user',
    content: '我的支付宝是 138****8888，麻烦尽快处理',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 3000000).toISOString(),
  },
  {
    id: 'demo-msg-2-8',
    conversation_id: 'demo-conv-2',
    role: 'assistant',
    content: '【系统】已为您转接人工客服',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 2900000).toISOString(),
  },

  // 物流配送咨询 (demo-conv-3) - 已结束评价
  {
    id: 'demo-msg-3-1',
    conversation_id: 'demo-conv-3',
    role: 'user',
    content: '我的快递怎么还没到？已经3天了',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-msg-3-2',
    conversation_id: 'demo-conv-3',
    role: 'assistant',
    content: '您好，我来帮您查询一下物流信息。请提供一下您的订单号或收件人手机号。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 86300000).toISOString(),
  },
  {
    id: 'demo-msg-3-3',
    conversation_id: 'demo-conv-3',
    role: 'user',
    content: '手机号 139****1234',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 86200000).toISOString(),
  },
  {
    id: 'demo-msg-3-4',
    conversation_id: 'demo-conv-3',
    role: 'assistant',
    content: '查询到您的包裹正在派送中，预计今天下午5点前送达。快递员是张师傅，电话 138****5678，如有问题可以直接联系。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 86100000).toISOString(),
  },
  {
    id: 'demo-msg-3-5',
    conversation_id: 'demo-conv-3',
    role: 'user',
    content: '好的，谢谢',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 43200000).toISOString(),
  },

  // 尺码选择帮助 (demo-conv-4)
  {
    id: 'demo-msg-4-1',
    conversation_id: 'demo-conv-4',
    role: 'user',
    content: '这件T恤选什么尺码合适？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'demo-msg-4-2',
    conversation_id: 'demo-conv-4',
    role: 'assistant',
    content: '您好！请问您能告诉我您的身高体重吗？这样我可以帮您推荐更合适的尺码。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 1700000).toISOString(),
  },
  {
    id: 'demo-msg-4-3',
    conversation_id: 'demo-conv-4',
    role: 'user',
    content: '我身高170cm，体重65kg',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 1600000).toISOString(),
  },
  {
    id: 'demo-msg-4-4',
    conversation_id: 'demo-conv-4',
    role: 'assistant',
    content: '根据您的身材数据，推荐您选择M码。这件T恤是正常尺码，M码对应身高165-175cm、体重60-70kg的顾客穿着效果最佳。偏瘦或喜欢宽松效果的也可以选L码。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 1500000).toISOString(),
  },
  {
    id: 'demo-msg-4-5',
    conversation_id: 'demo-conv-4',
    role: 'user',
    content: '那会不会缩水？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 400000).toISOString(),
  },
  {
    id: 'demo-msg-4-6',
    conversation_id: 'demo-conv-4',
    role: 'assistant',
    content: '这款T恤经过预缩水处理，首次洗涤后缩水率控制在3%以内，不影响正常穿着。建议洗涤时水温不要超过30度，避免暴晒，这样可以让衣服保持最佳状态。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 300000).toISOString(),
  },

  // 商品缺货咨询 (demo-conv-5)
  {
    id: 'demo-msg-5-1',
    conversation_id: 'demo-conv-5',
    role: 'user',
    content: '这件连衣裙还有货吗？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: 'demo-msg-5-2',
    conversation_id: 'demo-conv-5',
    role: 'assistant',
    content: '您好！您看中的这款连衣裙目前缺货，预计下周一会补货到仓库。您可以先下单，到货后我们会第一时间为您发出。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 5300000).toISOString(),
  },
  {
    id: 'demo-msg-5-3',
    conversation_id: 'demo-conv-5',
    role: 'user',
    content: '那我要先下单还是等有货再买？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 4000000).toISOString(),
  },
  {
    id: 'demo-msg-5-4',
    conversation_id: 'demo-conv-5',
    role: 'assistant',
    content: '建议您先下单哦！这样可以锁定库存，到货后系统会自动安排发货，无需您再操作。如果您等不及，也可以选择有货时再购买。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 1200000).toISOString(),
  },

  // 优惠券使用问题 (demo-conv-6)
  {
    id: 'demo-msg-6-1',
    conversation_id: 'demo-conv-6',
    role: 'user',
    content: '我有一张满200减50的优惠券，为什么不能用？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'demo-msg-6-2',
    conversation_id: 'demo-conv-6',
    role: 'assistant',
    content: '您好！我来帮您查一下优惠券的状态。请提供一下优惠券券号。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 172700000).toISOString(),
  },
  {
    id: 'demo-msg-6-3',
    conversation_id: 'demo-conv-6',
    role: 'user',
    content: '券号是 JZ20240615001',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 172600000).toISOString(),
  },
  {
    id: 'demo-msg-6-4',
    conversation_id: 'demo-conv-6',
    role: 'assistant',
    content: '查到了！您的优惠券是新人专享券，需要单笔订单金额满200元（不含运费）才能使用。您当前的购物车金额是185元，还差15元就能用券了。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 172500000).toISOString(),
  },
  {
    id: 'demo-msg-6-5',
    conversation_id: 'demo-conv-6',
    role: 'user',
    content: '原来是这样，那我再看看有没有别的东西要买',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 172400000).toISOString(),
  },
  {
    id: 'demo-msg-6-6',
    conversation_id: 'demo-conv-6',
    role: 'assistant',
    content: '好的！优惠券有效期到6月30日，建议您尽快使用哦。购物过程中有任何问题随时联系我。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 172300000).toISOString(),
  },
  {
    id: 'demo-msg-6-7',
    conversation_id: 'demo-conv-6',
    role: 'user',
    content: '好的，谢谢',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },

  // 地址修改请求 (demo-conv-7) - 已转人工
  {
    id: 'demo-msg-7-1',
    conversation_id: 'demo-conv-7',
    role: 'user',
    content: '我的订单还没发货，能帮我改一下地址吗？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'demo-msg-7-2',
    conversation_id: 'demo-conv-7',
    role: 'assistant',
    content: '您好！订单未发货前是可以修改收货地址的。请告诉我您的新地址，我帮您操作。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 10700000).toISOString(),
  },
  {
    id: 'demo-msg-7-3',
    conversation_id: 'demo-conv-7',
    role: 'user',
    content: '新地址是：上海市浦东新区张江镇科苑路88号，收件人王五，电话139****1234',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 10600000).toISOString(),
  },
  {
    id: 'demo-msg-7-4',
    conversation_id: 'demo-conv-7',
    role: 'assistant',
    content: '好的，正在为您修改地址...',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 10500000).toISOString(),
  },
  {
    id: 'demo-msg-7-5',
    conversation_id: 'demo-conv-7',
    role: 'assistant',
    content: '【系统】检测到需要核实身份，已为您转接人工客服',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 10400000).toISOString(),
  },

  // 会员积分兑换 (demo-conv-8)
  {
    id: 'demo-msg-8-1',
    conversation_id: 'demo-conv-8',
    role: 'user',
    content: '我有多少积分？可以换什么？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'demo-msg-8-2',
    conversation_id: 'demo-conv-8',
    role: 'assistant',
    content: '您好！我这边查询到您目前有3280会员积分。积分可以兑换以下礼品：50积分兑换5元无门槛优惠券、100积分兑换10元店铺红包、500积分兑换精美礼品一份、2000积分兑换免运费特权。您对哪个感兴趣？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 800000).toISOString(),
  },
  {
    id: 'demo-msg-8-3',
    conversation_id: 'demo-conv-8',
    role: 'user',
    content: '5元优惠券怎么兑换？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 450000).toISOString(),
  },

  // 发票开具咨询 (demo-conv-9)
  {
    id: 'demo-msg-9-1',
    conversation_id: 'demo-conv-9',
    role: 'user',
    content: '能开增值税专用发票吗？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'demo-msg-9-2',
    conversation_id: 'demo-conv-9',
    role: 'assistant',
    content: '您好！可以的。请提供以下开票信息：1. 公司名称 2. 纳税人识别号 3. 开户银行及账号 4. 注册地址和电话。我帮您提交开票申请。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 259100000).toISOString(),
  },
  {
    id: 'demo-msg-9-3',
    conversation_id: 'demo-conv-9',
    role: 'user',
    content: '公司名：上海智联科技有限公司，税号：91310000MA1K3XYZ12，银行：工商银行上海张江支行，账号：622202****8888，地址：上海市浦东新区张江高科技园区，的电话：021-88888888',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 259000000).toISOString(),
  },
  {
    id: 'demo-msg-9-4',
    conversation_id: 'demo-conv-9',
    role: 'assistant',
    content: '收到！开票信息已确认。发票会在7个工作日内开具并寄出，寄出后会有短信通知您。收货地址与订单地址一致可以吗？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },

  // 退换货流程咨询 (demo-conv-10)
  {
    id: 'demo-msg-10-1',
    conversation_id: 'demo-conv-10',
    role: 'user',
    content: '7天无理由退换货怎么操作？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 2700000).toISOString(),
  },
  {
    id: 'demo-msg-10-2',
    conversation_id: 'demo-conv-10',
    role: 'assistant',
    content: '您好！7天无理由退换货流程如下：1. 在"我的订单"中找到该商品，点击"申请退换"；2. 选择退换原因（不喜欢/尺码不合适/其他）；3. 提交后等待审核；4. 审核通过后，按提示寄回商品；5. 我们收到货后3个工作日内完成退款。请问您是因为什么原因想退换呢？',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 2600000).toISOString(),
  },
  {
    id: 'demo-msg-10-3',
    conversation_id: 'demo-conv-10',
    role: 'user',
    content: '尺码买大了，穿着不合适',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 2500000).toISOString(),
  },
  {
    id: 'demo-msg-10-4',
    conversation_id: 'demo-conv-10',
    role: 'assistant',
    content: '明白了！您可以选择换小一码或者直接退货。如果同款有货的话建议换货，这样更快。换货的话寄回后我们收到就会立刻发出新尺码，退货退款一般3-5个工作日到账。',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 2400000).toISOString(),
  },
  {
    id: 'demo-msg-10-5',
    conversation_id: 'demo-conv-10',
    role: 'user',
    content: '我再想想，谢谢',
    message_type: 'text',
    sources: null,
    created_at: new Date(Date.now() - 600000).toISOString(),
  },
];
