// Demo 客户数据（用于 customer-repository.ts 中的 list 方法内联定义）
export const DEMO_CUSTOMERS = [
  {
    id: 'demo-cust-1',
    name: '刘思思',
    phone: '138****1234',
    email: 'liuss@example.com',
    source_platform: 'taobao',
    tags: ['VIP', '高频'],
    notes: '优质客户',
    conversation_count: 12,
    last_seen_at: '2026-06-10T08:00:00Z',
    created_at: '2026-01-15T00:00:00Z',
    is_anonymous: false,
    platform_connection_id: null,
    external_id: 'tb-10001',
  },
  {
    id: 'demo-cust-2',
    name: '陈大伟',
    phone: '139****5678',
    email: 'chendw@example.com',
    source_platform: 'jd',
    tags: ['退换货'],
    notes: null,
    conversation_count: 5,
    last_seen_at: '2026-06-09T15:00:00Z',
    created_at: '2026-03-20T00:00:00Z',
    is_anonymous: false,
    platform_connection_id: null,
    external_id: 'jd-20001',
  },
  {
    id: 'demo-cust-3',
    name: '周小琳',
    phone: null,
    email: 'zhouxl@example.com',
    source_platform: 'web',
    tags: ['新客户'],
    notes: null,
    conversation_count: 1,
    last_seen_at: '2026-06-10T11:00:00Z',
    created_at: '2026-06-10T00:00:00Z',
    is_anonymous: false,
    platform_connection_id: null,
    external_id: 'visitor-uuid-1',
  },
  {
    id: 'demo-cust-4',
    name: '访客-abc123',
    phone: null,
    email: null,
    source_platform: 'web',
    tags: [],
    notes: null,
    conversation_count: 1,
    last_seen_at: '2026-06-10T12:00:00Z',
    created_at: '2026-06-10T12:00:00Z',
    is_anonymous: true,
    platform_connection_id: null,
    external_id: null,
  },
] as const;
