import type { KnowledgeItemWithNormalized } from '../knowledge-repository';

// Demo 知识库条目
export const DEMO_ITEMS: KnowledgeItemWithNormalized[] = [
  {
    id: 'demo-ki-1',
    name: '退换货政策',
    title: '退换货政策',
    type: 'text',
    content: '7天无理由退换货，需保持商品完好...',
    content_hash: null,
    doc_ids: [],
    category: '售后',
    parent_category: null,
    status: 'active',
    chunk_count: 3,
    hit_count: 12,
    last_hit_at: '2026-06-08T10:00:00Z',
    adopted_count: 9,
    rejected_count: 1,
    archived_at: null,
    expires_at: null,
    image_url: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: null,
  },
  {
    id: 'demo-ki-2',
    name: '配送时效说明',
    title: '配送时效说明',
    type: 'text',
    content: '标准快递3-5个工作日...',
    content_hash: null,
    doc_ids: [],
    category: '物流',
    parent_category: null,
    status: 'active',
    chunk_count: 2,
    hit_count: 8,
    last_hit_at: '2026-06-07T14:30:00Z',
    adopted_count: 5,
    rejected_count: 2,
    archived_at: null,
    expires_at: null,
    image_url: null,
    created_at: '2026-01-15T00:00:00Z',
    updated_at: null,
  },
  {
    id: 'demo-ki-3',
    name: '支付方式说明',
    title: '支付方式说明',
    type: 'text',
    content: '支持支付宝、微信、花呗分期...',
    content_hash: null,
    doc_ids: [],
    category: '支付',
    parent_category: null,
    status: 'active',
    chunk_count: 2,
    hit_count: 5,
    last_hit_at: '2026-06-06T09:15:00Z',
    adopted_count: 4,
    rejected_count: 0,
    archived_at: null,
    expires_at: null,
    image_url: null,
    created_at: '2026-02-01T00:00:00Z',
    updated_at: null,
  },
  {
    id: 'demo-ki-4',
    name: '会员权益说明',
    title: '会员权益说明',
    type: 'url',
    content: 'https://example.com/membership',
    content_hash: null,
    doc_ids: ['doc-1'],
    category: '会员',
    parent_category: null,
    status: 'archived',
    chunk_count: 5,
    hit_count: 3,
    last_hit_at: '2026-06-05T16:00:00Z',
    adopted_count: 1,
    rejected_count: 2,
    archived_at: '2026-06-10T00:00:00Z',
    expires_at: null,
    image_url: 'https://example.com/membership-benefits.png',
    created_at: '2026-03-01T00:00:00Z',
    updated_at: null,
  },
];
