-- supabase/policies/.snapshot.sql
-- AUTO-GENERATED by scripts/policies/generate-policies.js. Do not edit by hand.
-- File count: 62

-- >>> BEGIN agent_assignment_config.sql
-- Phase B / B1: explicit service-role pin for agent_assignment_config.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "agent_assignment_config_service_role_all" ON public.agent_assignment_config;
CREATE POLICY "agent_assignment_config_service_role_all"
  ON public.agent_assignment_config
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END agent_assignment_config.sql
-- >>> BEGIN agent_assignment_stats.sql
-- Phase B / B1: explicit service-role pin for agent_assignment_stats.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "agent_assignment_stats_service_role_all" ON public.agent_assignment_stats;
CREATE POLICY "agent_assignment_stats_service_role_all"
  ON public.agent_assignment_stats
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END agent_assignment_stats.sql
-- >>> BEGIN agent_collaborations.sql
-- Phase B / B1: explicit service-role pin for agent_collaborations.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "agent_collaborations_service_role_all" ON public.agent_collaborations;
CREATE POLICY "agent_collaborations_service_role_all"
  ON public.agent_collaborations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END agent_collaborations.sql
-- >>> BEGIN agent_delegations.sql
-- Phase B / B1: explicit service-role pin for agent_delegations.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "agent_delegations_service_role_all" ON public.agent_delegations;
CREATE POLICY "agent_delegations_service_role_all"
  ON public.agent_delegations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END agent_delegations.sql
-- >>> BEGIN agent_queue.sql
-- Phase B / B1: explicit service-role pin for agent_queue.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "agent_queue_service_role_all" ON public.agent_queue;
CREATE POLICY "agent_queue_service_role_all"
  ON public.agent_queue
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END agent_queue.sql
-- >>> BEGIN agent_sessions.sql
-- Phase B / B1: explicit service-role pin for agent_sessions.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "agent_sessions_service_role_all" ON public.agent_sessions;
CREATE POLICY "agent_sessions_service_role_all"
  ON public.agent_sessions
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END agent_sessions.sql
-- >>> BEGIN alerts.sql
-- Phase B / B1: explicit service-role pin for alerts.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "alerts_service_role_all" ON public.alerts;
CREATE POLICY "alerts_service_role_all"
  ON public.alerts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END alerts.sql
-- >>> BEGIN allowed_domains.sql
-- Phase B / B1: explicit service-role pin for allowed_domains.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "allowed_domains_service_role_all" ON public.allowed_domains;
CREATE POLICY "allowed_domains_service_role_all"
  ON public.allowed_domains
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END allowed_domains.sql
-- >>> BEGIN auto_reply_rules.sql
-- Phase B / B1: explicit service-role pin for auto_reply_rules.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "auto_reply_rules_service_role_all" ON public.auto_reply_rules;
CREATE POLICY "auto_reply_rules_service_role_all"
  ON public.auto_reply_rules
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END auto_reply_rules.sql
-- >>> BEGIN bot_configs.sql
-- Phase B / B1: explicit service-role pin for bot_configs.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "bot_configs_service_role_all" ON public.bot_configs;
CREATE POLICY "bot_configs_service_role_all"
  ON public.bot_configs
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END bot_configs.sql
-- >>> BEGIN content_filter_logs.sql
-- Phase B / B1: explicit service-role pin for content_filter_logs.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "content_filter_logs_service_role_all" ON public.content_filter_logs;
CREATE POLICY "content_filter_logs_service_role_all"
  ON public.content_filter_logs
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END content_filter_logs.sql
-- >>> BEGIN content_sensitive_words.sql
-- Phase B / B1: explicit service-role pin for content_sensitive_words.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "content_sensitive_words_service_role_all" ON public.content_sensitive_words;
CREATE POLICY "content_sensitive_words_service_role_all"
  ON public.content_sensitive_words
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END content_sensitive_words.sql
-- >>> BEGIN conversation_tag_records.sql
-- Phase B / B1: explicit service-role pin for conversation_tag_records.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "conversation_tag_records_service_role_all" ON public.conversation_tag_records;
CREATE POLICY "conversation_tag_records_service_role_all"
  ON public.conversation_tag_records
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END conversation_tag_records.sql
-- >>> BEGIN conversation_tags_def.sql
-- Phase B / B1: explicit service-role pin for conversation_tags_def.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "conversation_tags_def_service_role_all" ON public.conversation_tags_def;
CREATE POLICY "conversation_tags_def_service_role_all"
  ON public.conversation_tags_def
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END conversation_tags_def.sql
-- >>> BEGIN conversations.sql
-- Phase B / B1: explicit service-role pin for conversations.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "conversations_service_role_all" ON public.conversations;
CREATE POLICY "conversations_service_role_all"
  ON public.conversations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END conversations.sql
-- >>> BEGIN customer_conversations.sql
-- Phase B / B1: explicit service-role pin for customer_conversations.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "customer_conversations_service_role_all" ON public.customer_conversations;
CREATE POLICY "customer_conversations_service_role_all"
  ON public.customer_conversations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END customer_conversations.sql
-- >>> BEGIN customer_tags.sql
-- Phase B / B1: explicit service-role pin for customer_tags.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "customer_tags_service_role_all" ON public.customer_tags;
CREATE POLICY "customer_tags_service_role_all"
  ON public.customer_tags
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END customer_tags.sql
-- >>> BEGIN customers.sql
-- Phase B / B1: explicit service-role pin for customers.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "customers_service_role_all" ON public.customers;
CREATE POLICY "customers_service_role_all"
  ON public.customers
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END customers.sql
-- >>> BEGIN effect_outbox.sql
-- Phase B / B1: explicit service-role pin for effect_outbox.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "effect_outbox_service_role_all" ON public.effect_outbox;
CREATE POLICY "effect_outbox_service_role_all"
  ON public.effect_outbox
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END effect_outbox.sql
-- >>> BEGIN health_check.sql
-- Phase B / B1: explicit service-role pin for health_check.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "health_check_service_role_all" ON public.health_check;
CREATE POLICY "health_check_service_role_all"
  ON public.health_check
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END health_check.sql
-- >>> BEGIN knowledge_feedback.sql
-- Phase B / B1: explicit service-role pin for knowledge_feedback.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "knowledge_feedback_service_role_all" ON public.knowledge_feedback;
CREATE POLICY "knowledge_feedback_service_role_all"
  ON public.knowledge_feedback
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END knowledge_feedback.sql
-- >>> BEGIN knowledge_gap_signals.sql
-- Phase B / B1: explicit service-role pin for knowledge_gap_signals.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "knowledge_gap_signals_service_role_all" ON public.knowledge_gap_signals;
CREATE POLICY "knowledge_gap_signals_service_role_all"
  ON public.knowledge_gap_signals
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END knowledge_gap_signals.sql
-- >>> BEGIN knowledge_items.sql
-- Phase B / B1: explicit service-role pin for knowledge_items.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "knowledge_items_service_role_all" ON public.knowledge_items;
CREATE POLICY "knowledge_items_service_role_all"
  ON public.knowledge_items
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END knowledge_items.sql
-- >>> BEGIN knowledge_learning_queue.sql
-- Phase B / B1: explicit service-role pin for knowledge_learning_queue.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "knowledge_learning_queue_service_role_all" ON public.knowledge_learning_queue;
CREATE POLICY "knowledge_learning_queue_service_role_all"
  ON public.knowledge_learning_queue
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END knowledge_learning_queue.sql
-- >>> BEGIN knowledge_versions.sql
-- Phase B / B1: explicit service-role pin for knowledge_versions.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "knowledge_versions_service_role_all" ON public.knowledge_versions;
CREATE POLICY "knowledge_versions_service_role_all"
  ON public.knowledge_versions
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END knowledge_versions.sql
-- >>> BEGIN llm_models.sql
-- Phase B / B1: explicit service-role pin for llm_models.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "llm_models_service_role_all" ON public.llm_models;
CREATE POLICY "llm_models_service_role_all"
  ON public.llm_models
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END llm_models.sql
-- >>> BEGIN llm_providers.sql
-- Phase B / B1: explicit service-role pin for llm_providers.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "llm_providers_service_role_all" ON public.llm_providers;
CREATE POLICY "llm_providers_service_role_all"
  ON public.llm_providers
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END llm_providers.sql
-- >>> BEGIN login_events.sql
-- Phase B / B1: explicit service-role pin for login_events.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "login_events_service_role_all" ON public.login_events;
CREATE POLICY "login_events_service_role_all"
  ON public.login_events
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END login_events.sql
-- >>> BEGIN marketing_campaigns.sql
-- Phase B / B1: explicit service-role pin for marketing_campaigns.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "marketing_campaigns_service_role_all" ON public.marketing_campaigns;
CREATE POLICY "marketing_campaigns_service_role_all"
  ON public.marketing_campaigns
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END marketing_campaigns.sql
-- >>> BEGIN marketing_logs.sql
-- Phase B / B1: explicit service-role pin for marketing_logs.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "marketing_logs_service_role_all" ON public.marketing_logs;
CREATE POLICY "marketing_logs_service_role_all"
  ON public.marketing_logs
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END marketing_logs.sql
-- >>> BEGIN messages.sql
-- Phase B / B1: explicit service-role pin for messages.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "messages_service_role_all" ON public.messages;
CREATE POLICY "messages_service_role_all"
  ON public.messages
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END messages.sql
-- >>> BEGIN platform_connections.sql
-- Phase B / B1: explicit service-role pin for platform_connections.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "platform_connections_service_role_all" ON public.platform_connections;
CREATE POLICY "platform_connections_service_role_all"
  ON public.platform_connections
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END platform_connections.sql
-- >>> BEGIN product_details.sql
-- Phase B / B1: explicit service-role pin for product_details.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "product_details_service_role_all" ON public.product_details;
CREATE POLICY "product_details_service_role_all"
  ON public.product_details
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END product_details.sql
-- >>> BEGIN push_event_log.sql
-- Phase B / B1: explicit service-role pin for push_event_log.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "push_event_log_service_role_all" ON public.push_event_log;
CREATE POLICY "push_event_log_service_role_all"
  ON public.push_event_log
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END push_event_log.sql
-- >>> BEGIN push_records.sql
-- Phase B / B1: explicit service-role pin for push_records.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "push_records_service_role_all" ON public.push_records;
CREATE POLICY "push_records_service_role_all"
  ON public.push_records
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END push_records.sql
-- >>> BEGIN push_templates.sql
-- Phase B / B1: explicit service-role pin for push_templates.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "push_templates_service_role_all" ON public.push_templates;
CREATE POLICY "push_templates_service_role_all"
  ON public.push_templates
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END push_templates.sql
-- >>> BEGIN quality_checks.sql
-- Phase B / B1: explicit service-role pin for quality_checks.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "quality_checks_service_role_all" ON public.quality_checks;
CREATE POLICY "quality_checks_service_role_all"
  ON public.quality_checks
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END quality_checks.sql
-- >>> BEGIN quality_rules.sql
-- Phase B / B1: explicit service-role pin for quality_rules.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "quality_rules_service_role_all" ON public.quality_rules;
CREATE POLICY "quality_rules_service_role_all"
  ON public.quality_rules
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END quality_rules.sql
-- >>> BEGIN quick_replies.sql
-- Phase B / B1: explicit service-role pin for quick_replies.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "quick_replies_service_role_all" ON public.quick_replies;
CREATE POLICY "quick_replies_service_role_all"
  ON public.quick_replies
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END quick_replies.sql
-- >>> BEGIN role_permissions.sql
-- Phase B / B1: explicit service-role pin for role_permissions.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "role_permissions_service_role_all" ON public.role_permissions;
CREATE POLICY "role_permissions_service_role_all"
  ON public.role_permissions
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END role_permissions.sql
-- >>> BEGIN routing_rules.sql
-- Phase B / B1: explicit service-role pin for routing_rules.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "routing_rules_service_role_all" ON public.routing_rules;
CREATE POLICY "routing_rules_service_role_all"
  ON public.routing_rules
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END routing_rules.sql
-- >>> BEGIN schedules.sql
-- Phase B / B1: explicit service-role pin for schedules.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "schedules_service_role_all" ON public.schedules;
CREATE POLICY "schedules_service_role_all"
  ON public.schedules
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END schedules.sql
-- >>> BEGIN settings.sql
-- Phase B / B1: explicit service-role pin for settings.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "settings_service_role_all" ON public.settings;
CREATE POLICY "settings_service_role_all"
  ON public.settings
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END settings.sql
-- >>> BEGIN shop_agent_accounts.sql
-- Phase B / B1: explicit service-role pin for shop_agent_accounts.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "shop_agent_accounts_service_role_all" ON public.shop_agent_accounts;
CREATE POLICY "shop_agent_accounts_service_role_all"
  ON public.shop_agent_accounts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END shop_agent_accounts.sql
-- >>> BEGIN shop_agent_bindings.sql
-- Phase B / B1: explicit service-role pin for shop_agent_bindings.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "shop_agent_bindings_service_role_all" ON public.shop_agent_bindings;
CREATE POLICY "shop_agent_bindings_service_role_all"
  ON public.shop_agent_bindings
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END shop_agent_bindings.sql
-- >>> BEGIN shops.sql
-- Phase B / B1: explicit service-role pin for shops.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "shops_service_role_all" ON public.shops;
CREATE POLICY "shops_service_role_all"
  ON public.shops
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END shops.sql
-- >>> BEGIN simulation_conversations.sql
-- Phase B / B1: explicit service-role pin for simulation_conversations.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "simulation_conversations_service_role_all" ON public.simulation_conversations;
CREATE POLICY "simulation_conversations_service_role_all"
  ON public.simulation_conversations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END simulation_conversations.sql
-- >>> BEGIN simulation_messages.sql
-- Phase B / B1: explicit service-role pin for simulation_messages.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "simulation_messages_service_role_all" ON public.simulation_messages;
CREATE POLICY "simulation_messages_service_role_all"
  ON public.simulation_messages
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END simulation_messages.sql
-- >>> BEGIN size_chart_products.sql
-- Phase B / B1: explicit service-role pin for size_chart_products.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "size_chart_products_service_role_all" ON public.size_chart_products;
CREATE POLICY "size_chart_products_service_role_all"
  ON public.size_chart_products
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END size_chart_products.sql
-- >>> BEGIN size_chart_versions.sql
-- Phase B / B1: explicit service-role pin for size_chart_versions.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "size_chart_versions_service_role_all" ON public.size_chart_versions;
CREATE POLICY "size_chart_versions_service_role_all"
  ON public.size_chart_versions
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END size_chart_versions.sql
-- >>> BEGIN size_charts.sql
-- Phase B / B1: explicit service-role pin for size_charts.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "size_charts_service_role_all" ON public.size_charts;
CREATE POLICY "size_charts_service_role_all"
  ON public.size_charts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END size_charts.sql
-- >>> BEGIN skill_groups.sql
-- Phase B / B1: explicit service-role pin for skill_groups.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "skill_groups_service_role_all" ON public.skill_groups;
CREATE POLICY "skill_groups_service_role_all"
  ON public.skill_groups
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END skill_groups.sql
-- >>> BEGIN ticket_audit_log.sql
-- Phase B / B1: explicit service-role pin for ticket_audit_log.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "ticket_audit_log_service_role_all" ON public.ticket_audit_log;
CREATE POLICY "ticket_audit_log_service_role_all"
  ON public.ticket_audit_log
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END ticket_audit_log.sql
-- >>> BEGIN ticket_categories.sql
-- Phase B / B1: explicit service-role pin for ticket_categories.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "ticket_categories_service_role_all" ON public.ticket_categories;
CREATE POLICY "ticket_categories_service_role_all"
  ON public.ticket_categories
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END ticket_categories.sql
-- >>> BEGIN ticket_comments.sql
-- Phase B / B1: explicit service-role pin for ticket_comments.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "ticket_comments_service_role_all" ON public.ticket_comments;
CREATE POLICY "ticket_comments_service_role_all"
  ON public.ticket_comments
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END ticket_comments.sql
-- >>> BEGIN ticket_custom_fields.sql
-- Phase B / B1: explicit service-role pin for ticket_custom_fields.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "ticket_custom_fields_service_role_all" ON public.ticket_custom_fields;
CREATE POLICY "ticket_custom_fields_service_role_all"
  ON public.ticket_custom_fields
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END ticket_custom_fields.sql
-- >>> BEGIN ticket_field_values.sql
-- Phase B / B1: explicit service-role pin for ticket_field_values.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "ticket_field_values_service_role_all" ON public.ticket_field_values;
CREATE POLICY "ticket_field_values_service_role_all"
  ON public.ticket_field_values
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END ticket_field_values.sql
-- >>> BEGIN ticket_relations.sql
-- Phase B / B1: explicit service-role pin for ticket_relations.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "ticket_relations_service_role_all" ON public.ticket_relations;
CREATE POLICY "ticket_relations_service_role_all"
  ON public.ticket_relations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END ticket_relations.sql
-- >>> BEGIN ticket_status_log.sql
-- Phase B / B1: explicit service-role pin for ticket_status_log.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "ticket_status_log_service_role_all" ON public.ticket_status_log;
CREATE POLICY "ticket_status_log_service_role_all"
  ON public.ticket_status_log
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END ticket_status_log.sql
-- >>> BEGIN tickets.sql
-- Phase B / B1: explicit service-role pin for tickets.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "tickets_service_role_all" ON public.tickets;
CREATE POLICY "tickets_service_role_all"
  ON public.tickets
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END tickets.sql
-- >>> BEGIN users.sql
-- Phase B / B1: explicit service-role pin for users.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "users_service_role_all" ON public.users;
CREATE POLICY "users_service_role_all"
  ON public.users
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END users.sql
-- >>> BEGIN webhook_event_processed.sql
-- Phase B / B1: explicit service-role pin for webhook_event_processed.
-- The application layer connects with service_role (bypasses RLS);
-- these policies are explicit so the snapshot tooling has something
-- to diff against. Tighten to a USING predicate if you ever expose
-- this table to anon/authenticated roles.

DROP POLICY IF EXISTS "webhook_event_processed_service_role_all" ON public.webhook_event_processed;
CREATE POLICY "webhook_event_processed_service_role_all"
  ON public.webhook_event_processed
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- <<< END webhook_event_processed.sql
