/**
 * Policy snapshot writer + inventory checker.
 *
 * Reads every `<table>.sql` file under `supabase/policies/` and emits a
 * canonical snapshot at `supabase/policies/.snapshot.sql`. The snapshot is
 * the file CI diffs against — when policy files change, re-run this script
 * with `pnpm policies:snapshot:write` and commit the updated snapshot.
 *
 * Usage (via tsx — no transpilation step needed):
 *   pnpm policies:snapshot:write   # regenerate snapshot
 *   pnpm policies:snapshot:check   # verify snapshot is up-to-date (exit 1 if drift)
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, basename, relative } from 'node:path';

// Use process.cwd() for reliability across Node.js runtimes (tsx, vitest, node).
const REPO_ROOT = process.cwd();
const POLICIES_DIR = join(REPO_ROOT, 'supabase', 'policies');
const SNAPSHOT_PATH = join(POLICIES_DIR, '.snapshot.sql');
const INVENTORY_PATH = join(POLICIES_DIR, '.inventory.json');

function listPolicyFiles(): string[] {
  if (!existsSync(POLICIES_DIR)) return [];
  return readdirSync(POLICIES_DIR)
    .filter((f) => f.endsWith('.sql'))
    .filter((f) => f !== '.snapshot.sql')
    .sort();
}

function readPolicyBody(filename: string): string {
  return readFileSync(join(POLICIES_DIR, filename), 'utf8').trimEnd();
}

function buildSnapshot(): string {
  const files = listPolicyFiles();
  const header = [
    '-- supabase/policies/.snapshot.sql',
    '-- AUTO-GENERATED by scripts/policies/generate-policies.js. Do not edit by hand.',
    `-- File count: ${files.length}`,
    '',
  ].join('\n');
  const body = files
    .map((f) => `-- >>> BEGIN ${f}\n${readPolicyBody(f)}\n-- <<< END ${f}`)
    .join('\n');
  return header + '\n' + body + '\n';
}

function buildInventory(): { tables: string[]; policyFiles: string[] } {
  const files = listPolicyFiles();
  const tables = files.map((f) => basename(f, '.sql')).sort();
  return { tables, policyFiles: files };
}

function main(): void {
  const command = process.argv[2] ?? 'write';

  if (command === 'write') {
    const snapshot = buildSnapshot();
    writeFileSync(SNAPSHOT_PATH, snapshot, 'utf8');
    const inv = buildInventory();
    writeFileSync(INVENTORY_PATH, JSON.stringify(inv, null, 2) + '\n', 'utf8');
    console.log(`[snapshot] wrote ${relative(REPO_ROOT, SNAPSHOT_PATH)} (${inv.tables.length} tables)`);
    return;
  }

  if (command === 'check') {
    const expected = buildSnapshot();
    if (!existsSync(SNAPSHOT_PATH)) {
      console.error(`[snapshot] missing snapshot at ${relative(REPO_ROOT, SNAPSHOT_PATH)}`);
      console.error('  run `pnpm policies:snapshot:write` to create it.');
      process.exit(1);
    }
    const actual = readFileSync(SNAPSHOT_PATH, 'utf8');
    if (actual !== expected) {
      console.error('[snapshot] drift detected — regenerate with `pnpm policies:snapshot:write`');
      process.exit(1);
    }
    console.log(`[snapshot] ok (${listPolicyFiles().length} policy files)`);
    return;
  }

  console.error(`[snapshot] unknown command: ${command}`);
  process.exit(2);
}

main();
