/**
 * DDL Guard Script (B2).
 *
 * Rejects hand-written DDL in new migration files that create or modify
 * ordinary application tables.
 *
 * Allowlisted (always ok):
 *   - Extension-only migrations (CREATE EXTENSION, etc.)
 *   - RLS-only migrations (ENABLE/DISABLE ROW LEVEL SECURITY, GRANT/REVOKE)
 *   - Trigger/function-only migrations (CREATE FUNCTION, CREATE TRIGGER)
 *   - Seed-data-only migrations (INSERT INTO, COPY)
 *   - Index-only migrations (CREATE INDEX on existing tables)
 *   - Drizzle-kit generated output (first 5 lines contain GENERATED marker)
 *
 * Blocked (require drizzle-kit for application tables):
 *   - CREATE TABLE (plain, not IF NOT EXISTS)
 *   - DROP TABLE
 *   - ALTER TABLE ... ADD COLUMN / DROP COLUMN / ALTER COLUMN / RENAME
 *
 * Usage:
 *   pnpm ddls:guard    # exit 0 if clean, exit 1 + details if violations found
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join, basename } from 'node:path';

const REPO_ROOT = process.cwd();
const MIGRATIONS_DIR = join(REPO_ROOT, 'supabase', 'migrations');
const DRIZZLE_OUT_DIR = join(REPO_ROOT, 'supabase', 'migrations', 'drizzle');

// Single-line blocked patterns (matched against trimmed line start).
const BLOCKED_LINE_PATTERNS: Array<{ test: (line: string) => boolean; label: string }> = [
  {
    test: (line) => /\bCREATE\s+TABLE\b/i.test(line) && !/\bIF\s+NOT\s+EXISTS\b/i.test(line),
    label: 'CREATE TABLE (use drizzle-kit or IF NOT EXISTS)',
  },
  {
    test: (line) => /\bDROP\s+TABLE\b/i.test(line),
    label: 'DROP TABLE (use drizzle-kit)',
  },
  {
    test: (line) => /\bALTER\s+TABLE\b/i.test(line) && /\b(ADD|DROP)\s+COLUMN\b/i.test(line),
    label: 'ALTER TABLE ADD/DROP COLUMN (use drizzle-kit)',
  },
  {
    test: (line) => /\bALTER\s+TABLE\b/i.test(line) && /\bALTER\s+COLUMN\b/i.test(line),
    label: 'ALTER COLUMN (use drizzle-kit)',
  },
  {
    test: (line) => /\bALTER\s+TABLE\b/i.test(line) && /\bRENAME\b/i.test(line),
    label: 'ALTER TABLE RENAME (use drizzle-kit)',
  },
];

// Keywords that make a migration "special" and exempt it from DDL blocking.
// Even if the file contains blocked patterns, if it also contains special
// keywords it may be legitimately adding extensions/RLS/triggers/etc.
const SPECIAL_KEYWORDS = [
  'CREATE EXTENSION',
  'CREATE INDEX',         // indexes on existing tables are fine
  'CREATE UNIQUE INDEX',
  'DROP POLICY',
  'CREATE POLICY',
  'ENABLE ROW LEVEL SECURITY',
  'DISABLE ROW LEVEL SECURITY',
  'NO FORCE',
  'FORCE',
  'CREATE OR REPLACE FUNCTION',
  'CREATE FUNCTION',
  'CREATE PROCEDURE',
  'CREATE OR REPLACE PROCEDURE',
  'CREATE TRIGGER',
  'CREATE SEQUENCE',
  'CREATE OR REPLACE VIEW',
  'COMMENT ON',
  'GRANT',
  'REVOKE',
  'INSERT INTO',
  'COPY ',
  'GENERATED BY DRIZZLE-KIT',
];

function hasSpecialKeyword(content: string): boolean {
  return SPECIAL_KEYWORDS.some((kw) => content.includes(kw));
}

function isHistoricalMigration(file: string): boolean {
  // Historical migrations (pre-B2, applied before the DDL guard existed).
  // Pattern: filename starts with a date string like 20260627_...
  // These are excluded from the DDL guard.
  const name = basename(file);
  return /^\d{8}[_\-]/.test(name);
}

function scanMigration(file: string): string | null {
  const content = readFileSync(file, 'utf8');
  const relPath = basename(file);

  // Skip drizzle-kit generated output directory
  if (file.replace(/\\/g, '/').includes(DRIZZLE_OUT_DIR.replace(/\\/g, '/'))) return null;

  // Skip historical migrations (pre-B2, applied before the DDL guard existed).
  // These are identifiable by their date-prefixed filenames.
  if (isHistoricalMigration(file)) return null;

  // Skip if self-identifying as generated
  const first5 = content.split('\n').slice(0, 5).join('\n');
  if (first5.includes('GENERATED BY DRIZZLE-KIT')) return null;

  // If the file has special keywords, it's a special migration — skip.
  // This lets extension, RLS, trigger, index, and seed migrations through.
  if (hasSpecialKeyword(content)) return null;

  // Check each non-empty, non-comment line for blocked patterns.
  const lines = content.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    // Skip empty lines and comment-only lines
    if (!trimmed || trimmed.startsWith('--')) continue;
    for (const { test, label } of BLOCKED_LINE_PATTERNS) {
      if (test(trimmed)) {
        return `${relPath}:${i + 1}: blocked: ${label}\n  line: ${trimmed.slice(0, 80)}`;
      }
    }
  }

  return null;
}

function main(): void {
  const files = readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith('.sql'))
    .map((f) => join(MIGRATIONS_DIR, f))
    .sort();

  const violations: string[] = [];
  for (const file of files) {
    const result = scanMigration(file);
    if (result) violations.push(result);
  }

  if (violations.length === 0) {
    console.log('[ddl-guard] ok — no untracked hand-written DDL detected');
    console.log(`  scanned ${files.length} migration files`);
    return;
  }

  console.error('[ddl-guard] FAILED — hand-written DDL detected:');
  for (const v of violations) {
    console.error(`  ${v}`);
  }
  console.error('\nUse drizzle-kit to generate migrations for application table changes.');
  console.error('Add to SPECIAL_KEYWORDS in scripts/check-ddl.ts if this is intentional special DDL.');
  process.exit(1);
}

main();
