-- Migration: Seed initial role_permissions data
-- Purpose: Populate role_permissions with default values for all 13 resources × 3 actions × 3 roles
-- Run this AFTER 20260630_role_permissions_unique.sql (which adds the unique constraint)

-- Admin: full access to everything
INSERT INTO role_permissions (role, resource, action, allowed, created_at, updated_at) VALUES
  ('admin', 'conversations', 'read', true, NOW(), NOW()),
  ('admin', 'conversations', 'write', true, NOW(), NOW()),
  ('admin', 'conversations', 'delete', true, NOW(), NOW()),
  ('admin', 'knowledge', 'read', true, NOW(), NOW()),
  ('admin', 'knowledge', 'write', true, NOW(), NOW()),
  ('admin', 'knowledge', 'delete', true, NOW(), NOW()),
  ('admin', 'settings', 'read', true, NOW(), NOW()),
  ('admin', 'settings', 'write', true, NOW(), NOW()),
  ('admin', 'settings', 'delete', true, NOW(), NOW()),
  ('admin', 'team', 'read', true, NOW(), NOW()),
  ('admin', 'team', 'write', true, NOW(), NOW()),
  ('admin', 'team', 'delete', true, NOW(), NOW()),
  ('admin', 'customers', 'read', true, NOW(), NOW()),
  ('admin', 'customers', 'write', true, NOW(), NOW()),
  ('admin', 'customers', 'delete', true, NOW(), NOW()),
  ('admin', 'analytics', 'read', true, NOW(), NOW()),
  ('admin', 'analytics', 'write', true, NOW(), NOW()),
  ('admin', 'analytics', 'delete', true, NOW(), NOW()),
  ('admin', 'tickets', 'read', true, NOW(), NOW()),
  ('admin', 'tickets', 'write', true, NOW(), NOW()),
  ('admin', 'tickets', 'delete', true, NOW(), NOW()),
  ('admin', 'marketing', 'read', true, NOW(), NOW()),
  ('admin', 'marketing', 'write', true, NOW(), NOW()),
  ('admin', 'marketing', 'delete', true, NOW(), NOW()),
  ('admin', 'bots', 'read', true, NOW(), NOW()),
  ('admin', 'bots', 'write', true, NOW(), NOW()),
  ('admin', 'bots', 'delete', true, NOW(), NOW()),
  ('admin', 'sub_agents', 'read', true, NOW(), NOW()),
  ('admin', 'sub_agents', 'write', true, NOW(), NOW()),
  ('admin', 'sub_agents', 'delete', true, NOW(), NOW()),
  ('admin', 'routing', 'read', true, NOW(), NOW()),
  ('admin', 'routing', 'write', true, NOW(), NOW()),
  ('admin', 'routing', 'delete', true, NOW(), NOW()),
  ('admin', 'quality', 'read', true, NOW(), NOW()),
  ('admin', 'quality', 'write', true, NOW(), NOW()),
  ('admin', 'quality', 'delete', true, NOW(), NOW()),
  ('admin', 'push', 'read', true, NOW(), NOW()),
  ('admin', 'push', 'write', true, NOW(), NOW()),
  ('admin', 'push', 'delete', true, NOW(), NOW())
ON CONFLICT (role, resource, action) DO NOTHING;

-- Agent: read-write for conversations/knowledge/customers/tickets/marketing; read-only for rest
INSERT INTO role_permissions (role, resource, action, allowed, created_at, updated_at) VALUES
  ('agent', 'conversations', 'read', true, NOW(), NOW()),
  ('agent', 'conversations', 'write', true, NOW(), NOW()),
  ('agent', 'conversations', 'delete', false, NOW(), NOW()),
  ('agent', 'knowledge', 'read', true, NOW(), NOW()),
  ('agent', 'knowledge', 'write', true, NOW(), NOW()),
  ('agent', 'knowledge', 'delete', false, NOW(), NOW()),
  ('agent', 'settings', 'read', true, NOW(), NOW()),
  ('agent', 'settings', 'write', false, NOW(), NOW()),
  ('agent', 'settings', 'delete', false, NOW(), NOW()),
  ('agent', 'team', 'read', true, NOW(), NOW()),
  ('agent', 'team', 'write', false, NOW(), NOW()),
  ('agent', 'team', 'delete', false, NOW(), NOW()),
  ('agent', 'customers', 'read', true, NOW(), NOW()),
  ('agent', 'customers', 'write', true, NOW(), NOW()),
  ('agent', 'customers', 'delete', false, NOW(), NOW()),
  ('agent', 'analytics', 'read', true, NOW(), NOW()),
  ('agent', 'analytics', 'write', false, NOW(), NOW()),
  ('agent', 'analytics', 'delete', false, NOW(), NOW()),
  ('agent', 'tickets', 'read', true, NOW(), NOW()),
  ('agent', 'tickets', 'write', true, NOW(), NOW()),
  ('agent', 'tickets', 'delete', false, NOW(), NOW()),
  ('agent', 'marketing', 'read', true, NOW(), NOW()),
  ('agent', 'marketing', 'write', true, NOW(), NOW()),
  ('agent', 'marketing', 'delete', false, NOW(), NOW()),
  ('agent', 'bots', 'read', true, NOW(), NOW()),
  ('agent', 'bots', 'write', false, NOW(), NOW()),
  ('agent', 'bots', 'delete', false, NOW(), NOW()),
  ('agent', 'sub_agents', 'read', true, NOW(), NOW()),
  ('agent', 'sub_agents', 'write', false, NOW(), NOW()),
  ('agent', 'sub_agents', 'delete', false, NOW(), NOW()),
  ('agent', 'routing', 'read', true, NOW(), NOW()),
  ('agent', 'routing', 'write', false, NOW(), NOW()),
  ('agent', 'routing', 'delete', false, NOW(), NOW()),
  ('agent', 'quality', 'read', true, NOW(), NOW()),
  ('agent', 'quality', 'write', false, NOW(), NOW()),
  ('agent', 'quality', 'delete', false, NOW(), NOW()),
  ('agent', 'push', 'read', true, NOW(), NOW()),
  ('agent', 'push', 'write', false, NOW(), NOW()),
  ('agent', 'push', 'delete', false, NOW(), NOW())
ON CONFLICT (role, resource, action) DO NOTHING;

-- Observer: read-only to everything
INSERT INTO role_permissions (role, resource, action, allowed, created_at, updated_at) VALUES
  ('observer', 'conversations', 'read', true, NOW(), NOW()),
  ('observer', 'conversations', 'write', false, NOW(), NOW()),
  ('observer', 'conversations', 'delete', false, NOW(), NOW()),
  ('observer', 'knowledge', 'read', true, NOW(), NOW()),
  ('observer', 'knowledge', 'write', false, NOW(), NOW()),
  ('observer', 'knowledge', 'delete', false, NOW(), NOW()),
  ('observer', 'settings', 'read', true, NOW(), NOW()),
  ('observer', 'settings', 'write', false, NOW(), NOW()),
  ('observer', 'settings', 'delete', false, NOW(), NOW()),
  ('observer', 'team', 'read', true, NOW(), NOW()),
  ('observer', 'team', 'write', false, NOW(), NOW()),
  ('observer', 'team', 'delete', false, NOW(), NOW()),
  ('observer', 'customers', 'read', true, NOW(), NOW()),
  ('observer', 'customers', 'write', false, NOW(), NOW()),
  ('observer', 'customers', 'delete', false, NOW(), NOW()),
  ('observer', 'analytics', 'read', true, NOW(), NOW()),
  ('observer', 'analytics', 'write', false, NOW(), NOW()),
  ('observer', 'analytics', 'delete', false, NOW(), NOW()),
  ('observer', 'tickets', 'read', true, NOW(), NOW()),
  ('observer', 'tickets', 'write', false, NOW(), NOW()),
  ('observer', 'tickets', 'delete', false, NOW(), NOW()),
  ('observer', 'marketing', 'read', true, NOW(), NOW()),
  ('observer', 'marketing', 'write', false, NOW(), NOW()),
  ('observer', 'marketing', 'delete', false, NOW(), NOW()),
  ('observer', 'bots', 'read', true, NOW(), NOW()),
  ('observer', 'bots', 'write', false, NOW(), NOW()),
  ('observer', 'bots', 'delete', false, NOW(), NOW()),
  ('observer', 'sub_agents', 'read', true, NOW(), NOW()),
  ('observer', 'sub_agents', 'write', false, NOW(), NOW()),
  ('observer', 'sub_agents', 'delete', false, NOW(), NOW()),
  ('observer', 'routing', 'read', true, NOW(), NOW()),
  ('observer', 'routing', 'write', false, NOW(), NOW()),
  ('observer', 'routing', 'delete', false, NOW(), NOW()),
  ('observer', 'quality', 'read', true, NOW(), NOW()),
  ('observer', 'quality', 'write', false, NOW(), NOW()),
  ('observer', 'quality', 'delete', false, NOW(), NOW()),
  ('observer', 'push', 'read', true, NOW(), NOW()),
  ('observer', 'push', 'write', false, NOW(), NOW()),
  ('observer', 'push', 'delete', false, NOW(), NOW())
ON CONFLICT (role, resource, action) DO NOTHING;
